name = "ElectronDynamicsModels"
uuid = "acecdaf2-97b2-47e1-90eb-3efa7bb274e5"
version = "0.1.0-DEV"
authors = ["Sebastian Micluța-Câmpeanu <sebastian.mc95@proton.me> and contributors"]

[deps]
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[compat]
Aqua = "0.8"
JET = "0.10"
LinearAlgebra = "1.11.0"
ModelingToolkit = "10.10"
OrdinaryDiffEqNonlinearSolve = "1.10.0"
OrdinaryDiffEqRosenbrock = "1.11.0"
OrdinaryDiffEqVerner = "1.2.0"
PhysicalConstants = "0.2.3"
Plots = "1"
SciMLBase = "2.102.1"
Statistics = "1"
Symbolics = "6.43.0"
Test = "1.11"
Unitful = "1.21.0"
UnitfulAtomic = "1.0.0"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
LaserTypes = "5d4621ae-8e2e-4ea7-b0c9-17e8c1bdc54c"
OrdinaryDiffEqNonlinearSolve = "127b3ac7-2247-4354-8eb6-78cf4e7c58e8"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
OrdinaryDiffEqVerner = "79d7bb75-1356-48c1-b8c0-6832512096c2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "LaserTypes", "Test", "OrdinaryDiffEqNonlinearSolve", "OrdinaryDiffEqRosenbrock", "OrdinaryDiffEqVerner", "Plots", "SciMLBase", "Statistics"]
